### ISSUE TITLE
Cannot find autogold.Want("foo", ...) when using testify suite

### ISSUE THREAD

**Issue by kokizzu** [hexops/autogold#7] opened 2021-01-06 04:40 UTC
minimal example code, without autogold:
```
package foo_test

import (
        "testing"

        "github.com/stretchr/testify/assert"
        "github.com/stretchr/testify/suite"
)

type newUserStartTestSuite struct {
        suite.Suite
}

type NewUserStart string
const (
        Registration = `registration`
        EmailVerification = `email_verification`
        PhoneVerification = `phone_verification`
)
func (n *NewUserStart) String() string {
        return string(*n)
}

func (ts *newUserStartTestSuite) TestString() {
        var s NewUserStart

        s = Registration
        assert.Equal(ts.T(), s.String(), "registration")

        s = EmailVerification
        assert.Equal(ts.T(), s.String(), "email_verification")

        s = PhoneVerification
        assert.Equal(ts.T(), s.String(), "phone_verification")
}

func TestNewUserStartTestSuite(t *testing.T) {
        suite.Run(t, new(newUserStartTestSuite))
}
```

with autogold (the test case doesn't make sense, but this is the minimal to reproduce):
```
package foo_test

import (
        "testing"
        "github.com/hexops/autogold"
        "github.com/stretchr/testify/suite"
)

type newUserStartTestSuite struct {
        suite.Suite
}

type NewUserStart string
const (
        Registration = `registration`
        EmailVerification = `email_verification`
        PhoneVerification = `phone_verification`
)
func (n *NewUserStart) String() string {
        return string(*n)
}

func (ts *newUserStartTestSuite) TestString() {
        var s NewUserStart

        s = Registration
        want := autogold.Want("reg",nil)
        want.Equal(ts.T(), s.String())

        s = EmailVerification
        want = autogold.Want("ev",nil)
        want.Equal(ts.T(), s.String())

        s = PhoneVerification
        want = autogold.Want("pv",nil)
        want.Equal(ts.T(), s.String())
}

func TestNewUserStartTestSuite(t *testing.T) {
        suite.Run(t, new(newUserStartTestSuite))
}
```
the error `go test -v foo_test.go -update`
```
=== RUN   TestNewUserStartTestSuite
=== RUN   TestNewUserStartTestSuite/TestString
    want.go:119: autogold: foo_test.go: could not find autogold.Want("reg", ...) function call
--- FAIL: TestNewUserStartTestSuite (0.01s)
    --- FAIL: TestNewUserStartTestSuite/TestString (0.01s)
FAIL
FAIL    command-line-arguments  0.015s
FAIL
```

**Comment by slimsag** [comment] 2021-01-07 03:23
Thanks for filing, definitely looks like a bug of some sort. I will take a look this weekend.

**Comment by slimsag** [comment] 2021-01-08 04:13
Hey @kokizzu - I took a look and found what the problem is. The `autogold.Want("reg", ...)` call in your code here is not under the `TestNewUserStartTestSuite` function, which it currently must be so that the name (`reg` in this case) is only required to be unique within the scope of `TestNewUserStartTestSuite` rather than within the scope of the entire file.

I realize that's a bit annoying giving you're using this other testing framework, I have plans to remove the need for passing a name to `autogold.Want` at all which will also solve this issue for you. https://github.com/hexops/autogold/issues/11

I'll follow-up here once that is available for you to try.

**Comment by slimsag** [comment] 2021-01-08 04:17
If you want a quick workaround, you can use [this branch](https://github.com/hexops/autogold/pull/13) I have up which allows `autogold.Want()` calls anywhere but requires the name you pass in be unique within the scope of the entire file:

```
go get -u github.com/hexops/autogold@ac1903af84e46f53650aaf8492e83350325f11d8
```

should do the trick I think

**Comment by kokizzu** [comment] 2021-01-08 11:16
yes, will try for next project :3 thanks

**Comment by slimsag** [comment] 2022-12-20 21:07
Closing in favor of #11

**Closed by slimsag** 2022-12-20 21:07 UTC
